// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.11.4
// source: astraea.proto

package astraea

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Labels         []string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,2,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	Embedding      []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_astraea_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNodeRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateNodeRequest) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *CreateNodeRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_astraea_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Found          bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Id             uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Labels         []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,4,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	HasEmbedding   bool                   `protobuf:"varint,5,opt,name=has_embedding,json=hasEmbedding,proto3" json:"has_embedding,omitempty"`
	Error          string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_astraea_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetNodeResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetNodeResponse) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GetNodeResponse) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *GetNodeResponse) GetHasEmbedding() bool {
	if x != nil {
		return x.HasEmbedding
	}
	return false
}

func (x *GetNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,2,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_astraea_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNodeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNodeRequest) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_astraea_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteNodeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateEdgeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Source         uint64                 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Target         uint64                 `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	EdgeType       string                 `protobuf:"bytes,3,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,4,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	Weight         float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	ValidFrom      *wrappers.Int64Value   `protobuf:"bytes,6,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo        *wrappers.Int64Value   `protobuf:"bytes,7,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEdgeRequest) Reset() {
	*x = CreateEdgeRequest{}
	mi := &file_astraea_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeRequest) ProtoMessage() {}

func (x *CreateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEdgeRequest) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *CreateEdgeRequest) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *CreateEdgeRequest) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

func (x *CreateEdgeRequest) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *CreateEdgeRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateEdgeRequest) GetValidFrom() *wrappers.Int64Value {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *CreateEdgeRequest) GetValidTo() *wrappers.Int64Value {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type GetEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeRequest) Reset() {
	*x = GetEdgeRequest{}
	mi := &file_astraea_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeRequest) ProtoMessage() {}

func (x *GetEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeRequest.ProtoReflect.Descriptor instead.
func (*GetEdgeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{6}
}

func (x *GetEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEdgeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Found          bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Id             uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Source         uint64                 `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	Target         uint64                 `protobuf:"varint,4,opt,name=target,proto3" json:"target,omitempty"`
	EdgeType       string                 `protobuf:"bytes,5,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,6,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	Weight         float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`
	ValidFrom      *wrappers.Int64Value   `protobuf:"bytes,8,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo        *wrappers.Int64Value   `protobuf:"bytes,9,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	Error          string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEdgeResponse) Reset() {
	*x = GetEdgeResponse{}
	mi := &file_astraea_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeResponse) ProtoMessage() {}

func (x *GetEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeResponse.ProtoReflect.Descriptor instead.
func (*GetEdgeResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{7}
}

func (x *GetEdgeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetEdgeResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEdgeResponse) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *GetEdgeResponse) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *GetEdgeResponse) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

func (x *GetEdgeResponse) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *GetEdgeResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GetEdgeResponse) GetValidFrom() *wrappers.Int64Value {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *GetEdgeResponse) GetValidTo() *wrappers.Int64Value {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *GetEdgeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateEdgeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,2,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEdgeRequest) Reset() {
	*x = UpdateEdgeRequest{}
	mi := &file_astraea_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEdgeRequest) ProtoMessage() {}

func (x *UpdateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEdgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEdgeRequest) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

type DeleteEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeRequest) Reset() {
	*x = DeleteEdgeRequest{}
	mi := &file_astraea_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeRequest) ProtoMessage() {}

func (x *DeleteEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEdgeRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResponse) Reset() {
	*x = MutationResponse{}
	mi := &file_astraea_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResponse) ProtoMessage() {}

func (x *MutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResponse.ProtoReflect.Descriptor instead.
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{10}
}

func (x *MutationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MutationResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *MutationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NeighborsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	EdgeType      string                 `protobuf:"bytes,3,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborsRequest) Reset() {
	*x = NeighborsRequest{}
	mi := &file_astraea_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborsRequest) ProtoMessage() {}

func (x *NeighborsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborsRequest.ProtoReflect.Descriptor instead.
func (*NeighborsRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{11}
}

func (x *NeighborsRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NeighborsRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *NeighborsRequest) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

type NeighborEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        uint64                 `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	NodeId        uint64                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborEntry) Reset() {
	*x = NeighborEntry{}
	mi := &file_astraea_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborEntry) ProtoMessage() {}

func (x *NeighborEntry) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborEntry.ProtoReflect.Descriptor instead.
func (*NeighborEntry) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{12}
}

func (x *NeighborEntry) GetEdgeId() uint64 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

func (x *NeighborEntry) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type NeighborsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Neighbors     []*NeighborEntry       `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborsResponse) Reset() {
	*x = NeighborsResponse{}
	mi := &file_astraea_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborsResponse) ProtoMessage() {}

func (x *NeighborsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborsResponse.ProtoReflect.Descriptor instead.
func (*NeighborsResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{13}
}

func (x *NeighborsResponse) GetNeighbors() []*NeighborEntry {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *NeighborsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BfsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	MaxDepth      uint32                 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BfsRequest) Reset() {
	*x = BfsRequest{}
	mi := &file_astraea_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BfsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfsRequest) ProtoMessage() {}

func (x *BfsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfsRequest.ProtoReflect.Descriptor instead.
func (*BfsRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{14}
}

func (x *BfsRequest) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BfsRequest) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type BfsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Depth         uint32                 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BfsEntry) Reset() {
	*x = BfsEntry{}
	mi := &file_astraea_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BfsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfsEntry) ProtoMessage() {}

func (x *BfsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfsEntry.ProtoReflect.Descriptor instead.
func (*BfsEntry) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{15}
}

func (x *BfsEntry) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *BfsEntry) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type BfsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*BfsEntry            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BfsResponse) Reset() {
	*x = BfsResponse{}
	mi := &file_astraea_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BfsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfsResponse) ProtoMessage() {}

func (x *BfsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfsResponse.ProtoReflect.Descriptor instead.
func (*BfsResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{16}
}

func (x *BfsResponse) GetNodes() []*BfsEntry {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *BfsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShortestPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Weighted      bool                   `protobuf:"varint,3,opt,name=weighted,proto3" json:"weighted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortestPathRequest) Reset() {
	*x = ShortestPathRequest{}
	mi := &file_astraea_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortestPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortestPathRequest) ProtoMessage() {}

func (x *ShortestPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortestPathRequest.ProtoReflect.Descriptor instead.
func (*ShortestPathRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{17}
}

func (x *ShortestPathRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ShortestPathRequest) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ShortestPathRequest) GetWeighted() bool {
	if x != nil {
		return x.Weighted
	}
	return false
}

type ShortestPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Path          []uint64               `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Cost          *wrappers.DoubleValue  `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortestPathResponse) Reset() {
	*x = ShortestPathResponse{}
	mi := &file_astraea_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortestPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortestPathResponse) ProtoMessage() {}

func (x *ShortestPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortestPathResponse.ProtoReflect.Descriptor instead.
func (*ShortestPathResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{18}
}

func (x *ShortestPathResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ShortestPathResponse) GetPath() []uint64 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *ShortestPathResponse) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ShortestPathResponse) GetCost() *wrappers.DoubleValue {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *ShortestPathResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VectorSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	K             uint32                 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchRequest) Reset() {
	*x = VectorSearchRequest{}
	mi := &file_astraea_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchRequest) ProtoMessage() {}

func (x *VectorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchRequest.ProtoReflect.Descriptor instead.
func (*VectorSearchRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{19}
}

func (x *VectorSearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *VectorSearchRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

type VectorSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResult) Reset() {
	*x = VectorSearchResult{}
	mi := &file_astraea_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResult) ProtoMessage() {}

func (x *VectorSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResult.ProtoReflect.Descriptor instead.
func (*VectorSearchResult) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{20}
}

func (x *VectorSearchResult) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *VectorSearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type VectorSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*VectorSearchResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResponse) Reset() {
	*x = VectorSearchResponse{}
	mi := &file_astraea_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResponse) ProtoMessage() {}

func (x *VectorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResponse.ProtoReflect.Descriptor instead.
func (*VectorSearchResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{21}
}

func (x *VectorSearchResponse) GetResults() []*VectorSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *VectorSearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gql           string                 `protobuf:"bytes,1,opt,name=gql,proto3" json:"gql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_astraea_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{22}
}

func (x *QueryRequest) GetGql() string {
	if x != nil {
		return x.Gql
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_astraea_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{23}
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_astraea_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{24}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          bool                   `protobuf:"varint,1,opt,name=pong,proto3" json:"pong,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_astraea_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraea_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_astraea_proto_rawDescGZIP(), []int{25}
}

func (x *PingResponse) GetPong() bool {
	if x != nil {
		return x.Pong
	}
	return false
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_astraea_proto protoreflect.FileDescriptor

const file_astraea_proto_rawDesc = "" +
	"\n" +
	"\rastraea.proto\x12\aastraea\x1a\x1egoogle/protobuf/wrappers.proto\"r\n" +
	"\x11CreateNodeRequest\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12'\n" +
	"\x0fproperties_json\x18\x02 \x01(\tR\x0epropertiesJson\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xb3\x01\n" +
	"\x0fGetNodeResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12'\n" +
	"\x0fproperties_json\x18\x04 \x01(\tR\x0epropertiesJson\x12#\n" +
	"\rhas_embedding\x18\x05 \x01(\bR\fhasEmbedding\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"L\n" +
	"\x11UpdateNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0fproperties_json\x18\x02 \x01(\tR\x0epropertiesJson\"#\n" +
	"\x11DeleteNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x95\x02\n" +
	"\x11CreateEdgeRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x04R\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x04R\x06target\x12\x1b\n" +
	"\tedge_type\x18\x03 \x01(\tR\bedgeType\x12'\n" +
	"\x0fproperties_json\x18\x04 \x01(\tR\x0epropertiesJson\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12:\n" +
	"\n" +
	"valid_from\x18\x06 \x01(\v2\x1b.google.protobuf.Int64ValueR\tvalidFrom\x126\n" +
	"\bvalid_to\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\avalidTo\" \n" +
	"\x0eGetEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xcf\x02\n" +
	"\x0fGetEdgeResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x16\n" +
	"\x06source\x18\x03 \x01(\x04R\x06source\x12\x16\n" +
	"\x06target\x18\x04 \x01(\x04R\x06target\x12\x1b\n" +
	"\tedge_type\x18\x05 \x01(\tR\bedgeType\x12'\n" +
	"\x0fproperties_json\x18\x06 \x01(\tR\x0epropertiesJson\x12\x16\n" +
	"\x06weight\x18\a \x01(\x01R\x06weight\x12:\n" +
	"\n" +
	"valid_from\x18\b \x01(\v2\x1b.google.protobuf.Int64ValueR\tvalidFrom\x126\n" +
	"\bvalid_to\x18\t \x01(\v2\x1b.google.protobuf.Int64ValueR\avalidTo\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"L\n" +
	"\x11UpdateEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0fproperties_json\x18\x02 \x01(\tR\x0epropertiesJson\"#\n" +
	"\x11DeleteEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"c\n" +
	"\x10MutationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"]\n" +
	"\x10NeighborsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x1b\n" +
	"\tedge_type\x18\x03 \x01(\tR\bedgeType\"A\n" +
	"\rNeighborEntry\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\x04R\x06edgeId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x04R\x06nodeId\"_\n" +
	"\x11NeighborsResponse\x124\n" +
	"\tneighbors\x18\x01 \x03(\v2\x16.astraea.NeighborEntryR\tneighbors\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"?\n" +
	"\n" +
	"BfsRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\rR\bmaxDepth\"9\n" +
	"\bBfsEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\rR\x05depth\"L\n" +
	"\vBfsResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.astraea.BfsEntryR\x05nodes\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"U\n" +
	"\x13ShortestPathRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x1a\n" +
	"\bweighted\x18\x03 \x01(\bR\bweighted\"\xa0\x01\n" +
	"\x14ShortestPathResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04path\x18\x02 \x03(\x04R\x04path\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\x120\n" +
	"\x04cost\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\x04cost\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"9\n" +
	"\x13VectorSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\rR\x01k\"C\n" +
	"\x12VectorSearchResult\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"c\n" +
	"\x14VectorSearchResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.astraea.VectorSearchResultR\aresults\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\" \n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03gql\x18\x01 \x01(\tR\x03gql\"`\n" +
	"\rQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"\r\n" +
	"\vPingRequest\"<\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\bR\x04pong\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xa7\a\n" +
	"\x0eAstraeaService\x12C\n" +
	"\n" +
	"CreateNode\x12\x1a.astraea.CreateNodeRequest\x1a\x19.astraea.MutationResponse\x12<\n" +
	"\aGetNode\x12\x17.astraea.GetNodeRequest\x1a\x18.astraea.GetNodeResponse\x12C\n" +
	"\n" +
	"UpdateNode\x12\x1a.astraea.UpdateNodeRequest\x1a\x19.astraea.MutationResponse\x12C\n" +
	"\n" +
	"DeleteNode\x12\x1a.astraea.DeleteNodeRequest\x1a\x19.astraea.MutationResponse\x12C\n" +
	"\n" +
	"CreateEdge\x12\x1a.astraea.CreateEdgeRequest\x1a\x19.astraea.MutationResponse\x12<\n" +
	"\aGetEdge\x12\x17.astraea.GetEdgeRequest\x1a\x18.astraea.GetEdgeResponse\x12C\n" +
	"\n" +
	"UpdateEdge\x12\x1a.astraea.UpdateEdgeRequest\x1a\x19.astraea.MutationResponse\x12C\n" +
	"\n" +
	"DeleteEdge\x12\x1a.astraea.DeleteEdgeRequest\x1a\x19.astraea.MutationResponse\x12B\n" +
	"\tNeighbors\x12\x19.astraea.NeighborsRequest\x1a\x1a.astraea.NeighborsResponse\x120\n" +
	"\x03Bfs\x12\x13.astraea.BfsRequest\x1a\x14.astraea.BfsResponse\x12K\n" +
	"\fShortestPath\x12\x1c.astraea.ShortestPathRequest\x1a\x1d.astraea.ShortestPathResponse\x12K\n" +
	"\fVectorSearch\x12\x1c.astraea.VectorSearchRequest\x1a\x1d.astraea.VectorSearchResponse\x126\n" +
	"\x05Query\x12\x15.astraea.QueryRequest\x1a\x16.astraea.QueryResponse\x123\n" +
	"\x04Ping\x12\x14.astraea.PingRequest\x1a\x15.astraea.PingResponseB1Z/github.com/jimeharrisjr/astraeadb-go/pb/astraeab\x06proto3"

var (
	file_astraea_proto_rawDescOnce sync.Once
	file_astraea_proto_rawDescData []byte
)

func file_astraea_proto_rawDescGZIP() []byte {
	file_astraea_proto_rawDescOnce.Do(func() {
		file_astraea_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraea_proto_rawDesc), len(file_astraea_proto_rawDesc)))
	})
	return file_astraea_proto_rawDescData
}

var file_astraea_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_astraea_proto_goTypes = []any{
	(*CreateNodeRequest)(nil),    // 0: astraea.CreateNodeRequest
	(*GetNodeRequest)(nil),       // 1: astraea.GetNodeRequest
	(*GetNodeResponse)(nil),      // 2: astraea.GetNodeResponse
	(*UpdateNodeRequest)(nil),    // 3: astraea.UpdateNodeRequest
	(*DeleteNodeRequest)(nil),    // 4: astraea.DeleteNodeRequest
	(*CreateEdgeRequest)(nil),    // 5: astraea.CreateEdgeRequest
	(*GetEdgeRequest)(nil),       // 6: astraea.GetEdgeRequest
	(*GetEdgeResponse)(nil),      // 7: astraea.GetEdgeResponse
	(*UpdateEdgeRequest)(nil),    // 8: astraea.UpdateEdgeRequest
	(*DeleteEdgeRequest)(nil),    // 9: astraea.DeleteEdgeRequest
	(*MutationResponse)(nil),     // 10: astraea.MutationResponse
	(*NeighborsRequest)(nil),     // 11: astraea.NeighborsRequest
	(*NeighborEntry)(nil),        // 12: astraea.NeighborEntry
	(*NeighborsResponse)(nil),    // 13: astraea.NeighborsResponse
	(*BfsRequest)(nil),           // 14: astraea.BfsRequest
	(*BfsEntry)(nil),             // 15: astraea.BfsEntry
	(*BfsResponse)(nil),          // 16: astraea.BfsResponse
	(*ShortestPathRequest)(nil),  // 17: astraea.ShortestPathRequest
	(*ShortestPathResponse)(nil), // 18: astraea.ShortestPathResponse
	(*VectorSearchRequest)(nil),  // 19: astraea.VectorSearchRequest
	(*VectorSearchResult)(nil),   // 20: astraea.VectorSearchResult
	(*VectorSearchResponse)(nil), // 21: astraea.VectorSearchResponse
	(*QueryRequest)(nil),         // 22: astraea.QueryRequest
	(*QueryResponse)(nil),        // 23: astraea.QueryResponse
	(*PingRequest)(nil),          // 24: astraea.PingRequest
	(*PingResponse)(nil),         // 25: astraea.PingResponse
	(*wrappers.Int64Value)(nil),  // 26: google.protobuf.Int64Value
	(*wrappers.DoubleValue)(nil), // 27: google.protobuf.DoubleValue
}
var file_astraea_proto_depIdxs = []int32{
	26, // 0: astraea.CreateEdgeRequest.valid_from:type_name -> google.protobuf.Int64Value
	26, // 1: astraea.CreateEdgeRequest.valid_to:type_name -> google.protobuf.Int64Value
	26, // 2: astraea.GetEdgeResponse.valid_from:type_name -> google.protobuf.Int64Value
	26, // 3: astraea.GetEdgeResponse.valid_to:type_name -> google.protobuf.Int64Value
	12, // 4: astraea.NeighborsResponse.neighbors:type_name -> astraea.NeighborEntry
	15, // 5: astraea.BfsResponse.nodes:type_name -> astraea.BfsEntry
	27, // 6: astraea.ShortestPathResponse.cost:type_name -> google.protobuf.DoubleValue
	20, // 7: astraea.VectorSearchResponse.results:type_name -> astraea.VectorSearchResult
	0,  // 8: astraea.AstraeaService.CreateNode:input_type -> astraea.CreateNodeRequest
	1,  // 9: astraea.AstraeaService.GetNode:input_type -> astraea.GetNodeRequest
	3,  // 10: astraea.AstraeaService.UpdateNode:input_type -> astraea.UpdateNodeRequest
	4,  // 11: astraea.AstraeaService.DeleteNode:input_type -> astraea.DeleteNodeRequest
	5,  // 12: astraea.AstraeaService.CreateEdge:input_type -> astraea.CreateEdgeRequest
	6,  // 13: astraea.AstraeaService.GetEdge:input_type -> astraea.GetEdgeRequest
	8,  // 14: astraea.AstraeaService.UpdateEdge:input_type -> astraea.UpdateEdgeRequest
	9,  // 15: astraea.AstraeaService.DeleteEdge:input_type -> astraea.DeleteEdgeRequest
	11, // 16: astraea.AstraeaService.Neighbors:input_type -> astraea.NeighborsRequest
	14, // 17: astraea.AstraeaService.Bfs:input_type -> astraea.BfsRequest
	17, // 18: astraea.AstraeaService.ShortestPath:input_type -> astraea.ShortestPathRequest
	19, // 19: astraea.AstraeaService.VectorSearch:input_type -> astraea.VectorSearchRequest
	22, // 20: astraea.AstraeaService.Query:input_type -> astraea.QueryRequest
	24, // 21: astraea.AstraeaService.Ping:input_type -> astraea.PingRequest
	10, // 22: astraea.AstraeaService.CreateNode:output_type -> astraea.MutationResponse
	2,  // 23: astraea.AstraeaService.GetNode:output_type -> astraea.GetNodeResponse
	10, // 24: astraea.AstraeaService.UpdateNode:output_type -> astraea.MutationResponse
	10, // 25: astraea.AstraeaService.DeleteNode:output_type -> astraea.MutationResponse
	10, // 26: astraea.AstraeaService.CreateEdge:output_type -> astraea.MutationResponse
	7,  // 27: astraea.AstraeaService.GetEdge:output_type -> astraea.GetEdgeResponse
	10, // 28: astraea.AstraeaService.UpdateEdge:output_type -> astraea.MutationResponse
	10, // 29: astraea.AstraeaService.DeleteEdge:output_type -> astraea.MutationResponse
	13, // 30: astraea.AstraeaService.Neighbors:output_type -> astraea.NeighborsResponse
	16, // 31: astraea.AstraeaService.Bfs:output_type -> astraea.BfsResponse
	18, // 32: astraea.AstraeaService.ShortestPath:output_type -> astraea.ShortestPathResponse
	21, // 33: astraea.AstraeaService.VectorSearch:output_type -> astraea.VectorSearchResponse
	23, // 34: astraea.AstraeaService.Query:output_type -> astraea.QueryResponse
	25, // 35: astraea.AstraeaService.Ping:output_type -> astraea.PingResponse
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_astraea_proto_init() }
func file_astraea_proto_init() {
	if File_astraea_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraea_proto_rawDesc), len(file_astraea_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraea_proto_goTypes,
		DependencyIndexes: file_astraea_proto_depIdxs,
		MessageInfos:      file_astraea_proto_msgTypes,
	}.Build()
	File_astraea_proto = out.File
	file_astraea_proto_goTypes = nil
	file_astraea_proto_depIdxs = nil
}
